#!/bin/bash

# Commits and pushes my zsh dotfiles
cd "${DOTSREPO}"

# include vimrc since I often edit it too
cp "${HOME}/.vimrc" .

# and my tmux config
cp "${HOME}/.tmux.conf" .

# where oh-my-zsh looks for config files
cp "${HOME}/.zshenv" .

cp "${ZDOTDIR}/.zshrc" .
cp "${ALIASES}" .
ditto "${SCRIPTS} ./"${SCRIPTS}"

git add -A
if [ -z "$1" ]; then
    git commit
else
    git commit -m "$1"
fi

git push
cd "$OLDPWD"


