#!/bin/zsh

# searches safari for the given string
# only works with .com, maybe make a more general check, i.e. one word and contains a .
function safari() {
		fin=$(echo $@ | rev | cut -c 1-4 | rev)
		if [[ $@ == *".com"* ]]; then
			open -a Safari "https://www.${@}"
		else
			complete_query_string="https://www.google.com/search?q=" #format: https://www.google.com/search?q=something+to+search+on+Google
			partial_query_string=""
			for i in $@; do
				partial_query_string=$partial_query_string+$i
			done
			partial_query_string=${partial_query_string:1} #useful for delete the first "+" 
			complete_query_string=$complete_query_string$partial_query_string
			open -a Safari $complete_query_string
		fi
}
