#!/bin/zsh

  # # # # # # # # # # # # # # # # # # # # # # # # #	  
#    ___    __    ____   ___    ____   ____   ____	#
#   / _ |  / /   /  _/  / _ |  / __/  / __/  / __/	#
#  / __ | / /__ _/ /   / __ | _\ \   / _/   _\ \  	#
# /_/ |_|/____//___/  /_/ |_|/___/  /___/  /___/  	#
#                                                 	#
  # # # # # # # # # # # # # # # # # # # # # # # # # 

# alias vim to my editor
alias vim="${EDITOR}"

#aliases for python -- be careful here!
alias python="python3" 
alias pip="pip3"

#aliases for zsh
alias zshsource="source ${ZDOTDIR}/.zshrc"
alias zshenv="${EDITOR} ${HOME}/.zshenv"
alias scr="cd ${SCRIPTS}"

# convienence aliases -- makes workflow faster
alias jn="jupyter notebook"
alias ip="ipython"
alias c="clear"
alias e="${EDITOR}"
alias s="fzf"

# aliases for brew
alias bi="brew info"
alias bcl="brew cask list"
alias bis="brew install"

# aliases for moving around file system
alias proj="cd ${PROJECTS}"
alias desk="cd ${HOME}/Desktop"
alias down="cd ${HOME}/Downloads"
alias dots="cd ${ZDOTDIR}"
alias ideas="${EDITOR} ${SCRIPTS}/.project_ideas.txt"

# aliases for conda 
alias el="conda env list"
alias cl="conda list"
alias ca="conda activate"
alias cc="conda create"
alias cda="conda deactivate"

# aliases for git
alias gs="git status"
alias gpl="git pull"
alias gdh="git diff HEAD"

# aliases for git workflow
alias gitignore="${EDITOR} .gitignore"
alias README="${EDITOR} README.md"

# aliases for common shell commands
alias vimrc="${EDITOR} ${HOME}/.vimrc"
alias vimrcsource="source ${HOME}/.vimrc"
alias ls="exa"
alias sl="ls"
alias tmuxconf="${EDITOR} ${HOME}/.tmux.conf"

# aliases for yadm
alias ya="yadm add"
alias yaa="yadm add -A"

alias ys="yadm status"
alias yc="yadm commit"
alias yp="yadm push"
alias yd="yadm diff"
alias ydh="yadm diff HEAD"
alias ypl="yadm pull"

alias ygitignore="${EDITOR} ${HOME}/.gitignore"
alias ylog="yadm log"
alias yreflog="yadm reflog"

alias yrh="yadm reset --hard"
alias yrs="yadm reset --soft"
alias yr="yadm reset"
alias yca="yadm commit --amend"
alias yrm="yadm rm"

alias ystrap="${EDITOR} ${HOME}/.config/yadm/bootstrap"

# aliases for system 
alias ram="top -l 1 -s 0 | grep PhysMem"
alias monitor='open -a "Activity Monitor"'
