#!/bin/zsh

  # # # # # # # # # # # # # # # # # # # # # # # # #	  
#    ___    __    ____   ___    ____   ____   ____	#
#   / _ |  / /   /  _/  / _ |  / __/  / __/  / __/	#
#  / __ | / /__ _/ /   / __ | _\ \   / _/   _\ \  	#
# /_/ |_|/____//___/  /_/ |_|/___/  /___/  /___/  	#
#                                                 	#
  # # # # # # # # # # # # # # # # # # # # # # # # # 

#aliases for python -- be careful here!
alias python="python3" 
alias pip="pip3"

#aliases for zsh
alias zshaliases="vim ${ALIASES}"
alias zshsource="source ${ZDOTDIR}/.zshrc"
alias zshconfig="vim ${ZDOTDIR}/.zshrc"
alias zshenv="vim ${HOME}/.zshenv"
alias fnc="cd ${SCRIPTS}"

# convienence aliases -- makes workflow faster
alias jn="jupyter notebook"
alias ip="ipython"
alias c="clear"
alias e="open -e"
alias v="vim"
alias s="fzf"

# aliases for moving around file system
alias proj="cd ${PROJECTS}"
alias desk="cd ${HOME}/Desktop"
alias down="cd ${HOME}/Downloads"
alias dots="cd ${ZDOTDIR}"
alias ideas="vim ${SCRIPTS}/.project_ideas.txt"

# aliases for conda 
alias el="conda env list"
alias ca="conda activate"
alias cc="conda create"
alias cda="conda deactivate"

# aliases for git
alias gs="git status"
alias gpl="git pull"

# aliases for git workflow
alias gitignore="vim .gitignore"
alias README="vim README.md"

# aliases for common shell commands
alias vimrc="vim ${HOME}/.vimrc"
alias vimrcsource="source ${HOME}/.vimrc"
alias ls="exa"
alias sl="ls"
alias lh="ls -ld .?*" # show only hidden files
alias lsh="ls -ld .?* | grep .zsh"

# aliases for yadm
alias ya="yadm add"
alias yaa="yadm add -A"
alias ys="yadm status"
alias yc="yadm commit"
alias yp="yadm push"
alias yd="yadm diff"
alias yl="yadm list -a"
alias ypl="yadm pull"
alias ygitignore="vim ${HOME}/.gitignore"
alias ylog="yadm log"
alias yreflog="yadm reflog"
alias yrhh="yadm reset --hard HEAD"
alias yrsh="yadm reset --soft HEAD"
alias yrh="yadm reset"
alias yca="yadm commit --amend"
alias ydc="yadm diff --cached"

# aliases for system stats
alias ram="top -l 1 -s 0 | grep PhysMem"

# alias since I'm lazy
alias fix="fuck"

# useless
alias asdf="echo "asdf""
