#!/bin/zsh

# All custom things that need to be added to my path should go in this file
# to edit it, run "epath"
export PATH="\
${SCRIPTS}:\
${HOME}/Library/Python/3.8/bin:\
${HOME}/.local/bin:\
${HOME}/.local/lib/python3.7/site-packages:\
${GOPATH}/bin:\
${HOME}/.rbenv/bin:\
${PATH}"

