#!/bin/zsh

echo -e "\033[32mCalling ~/.config/yadm/bootstrap...\033[0m"

if [[ "$OSTYPE" != "darwin"* ]]; then
	echo "Not on a Mac, exiting..."
	exit 1
fi

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

if ! [ -x "$(command -v brew)" ]; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
	echo -e "\033[32mbrew installed... continuing\033[0m"
fi

echo -e "\033[32mInstalling packages from Brewfile...\033[0m"
brew bundle --file="${HOME}/.config/Brewfile" install

if ! [ -x "$(command -v rbenv)" ]; then
	brew install rbenv
	rbenv install 2.7.1
	rbenv global 2.7.1
else
	echo -e "\033[32mrbenv installed... continuing\033[0m"
fi

mkdir -p "${HOME}/Documents/Projects"
cd "${HOME}/Documents/Projects"

echo -e "\033[32mCloning projects...\033[0m"

git clone https://github.com/jlehrer1/BTT-Practical.git
git clone https://github.com/jlehrer1/Misc.git
git clone https://github.com/jlehrer1/Projects.git
git clone https://github.com/jlehrer1/InstantEDA.git
git clone https://github.com/jlehrer1/resume.git
git clone https://github.com/jlehrer1/quick_model.git
git clone https://github.com/jlehrer1/DengAI.git
git clone https://github.com/jlehrer1/personal-website.git

cd "${OLDPWD}"

echo "\033[32mFinished basic setup... please restart Terminal\033[0m"
