#!/usr/bin/env bash

# searches recursively in my zsh config and zsh install folder for the regex pattern
# useful for finding aliases
if [ "$1" == '-m' ]; then
	grep -r "${@:2}" --color=auto "${ZDOTDIR}/.zshrc" "${DOTS}"
else 
	grep -r "$@" --color=auto --exclude=".zsh_history" "${ZDOTDIR}" "${ZSH}" "${HOME}/.zshenv"
fi
