#!/bin/zsh

# git diff my current zsh setup with my git repo
function zshdiff() {
	cd ~/Documents/Projects/System/zsh
	ditto "${HOME}/.zsh_functions" ./.zsh_functions	
	cp "${HOME}/.zshrc" .
	cp "${HOME}/.zsh_aliases" .
	git add -A
	git diff
	git reset --hard HEAD >/dev/null 2>&1
	printf "HEAD log is: "
	git log -n 1 | cat | tail -n 1 | xargs
	cd $OLDPWD	
}
