#!/bin/zsh

# reverts zsh-things to the previous head
zshrevert() {
	cd "${HOME}/Documents/Projects/System/zsh"
	cp .zshrc ~
	cp -R .zsh_functions ~/.zsh_functions
	cp .zsh_aliases ~
	
	echo "Reverting .zsh things to HEAD..."
}

