#!/bin/zsh

  # # # # # # # # # # # # # # # # # # # # # # # # #	  
#    ___    __    ____   ___    ____   ____   ____	#
#   / _ |  / /   /  _/  / _ |  / __/  / __/  / __/	#
#  / __ | / /__ _/ /   / __ | _\ \   / _/   _\ \  	#
# /_/ |_|/____//___/  /_/ |_|/___/  /___/  /___/  	#
#                                                 	#
  # # # # # # # # # # # # # # # # # # # # # # # # # 

# alias vim to my editor
alias vim="${EDITOR}"

#aliases for python -- be careful here!
alias python="python3" 
alias pip="pip3"

#aliases for pip
alias pi="pip install"
alias piup="pip install --upgrade"

#aliases for zsh
alias zshsource="source ${ZDOTDIR}/.zshrc"
alias zshenv="${EDITOR} ${HOME}/.zshenv"
alias als="cd ${ALIASES}"
alias scr="cd ${SCRIPTS}"

# convienence aliases -- makes workflow faster
alias jn="jupyter notebook"
alias ip="ipython"
alias c="clear"
alias e="${EDITOR}"
alias s="fzf"
alias rmrf="rm -rf"

# aliases for brew
alias bi="brew info"
alias bcl="brew cask list"
alias bis="brew install"

# aliases for moving around file system
alias proj="cd ${PROJECTS}"
alias desk="cd ${HOME}/Desktop"
alias down="cd ${HOME}/Downloads"
alias dots="cd ${ZDOTDIR}"
alias ideas="${EDITOR} ${ZDOTDIR}/personal/project_ideas.txt"
alias todo="${EDITOR} ${ZDOTDIR}/personal/todo.txt"
alias brewfile="${EDITOR} ${HOME}/.config/Brewfile"

# aliases for conda 
alias cl="conda list"
alias ca="conda activate"
alias cc="conda create"
alias cda="conda deactivate"

# aliases for common shell commands
alias vimrc="${EDITOR} ${HOME}/.vimrc"
alias vimrcsource="source ${HOME}/.vimrc"
alias ls="exa"
alias sl="ls"

# aliases for system 
alias ram="top -l 1 -s 0 | grep PhysMem"
alias monitor='open -a "Activity Monitor"'
