#!/bin/zsh

# aliases for yadm
alias ya="yadm add"
alias yaa="yadm add -A"
alias yaf="yadm add -f"

alias ys="yadm status -u"
alias yc="yadm commit"
alias yp="yadm push"
alias yd="yadm diff"
alias ydh="yadm diff HEAD"
alias ypl="yadm pull"

alias ylog="yadm log"
alias yreflog="yadm reflog"
alias yconfig="${EDITOR} ${HOME}/.config/yadm/config"

alias yrh="yadm reset --hard"
alias yrs="yadm reset --soft"
alias yr="yadm reset"
alias yrhh="yadm reset --hard HEAD"
alias yca="yadm commit --amend"

alias yrm="yadm rm"
alias yrmc="yadm rm --cached"

alias ystrap="${EDITOR} ${HOME}/.config/yadm/bootstrap"

