#!/bin/bash

# shows currently installed packages that are not saved to brew_packages.txt
diff <(cat ~/Documents/Projects/System/packages/brew_packages.txt | sort) <(brew leaves | sort) | grep "^>" | awk '{print $2}'

