#!/usr/bin/env bash


# appends arguments to path if not already included
for ARG in "$@"
do
	if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="${PATH:+"$PATH:"}$ARG"
    fi
done

