#!/bin/bash

# either vim's into a new file for a new function (if -n), or lists my custom
# functions so one can be edited
if [[ $1 == "-n" ]]; then
	vim "${SCRIPTS}/${2}"	
else
	vim "${SCRIPTS}"
fi

