#!/bin/bash

# searches recursively in my zsh config and zsh install folder for the regex pattern
# useful for finding aliases
grep -r "$@" --color=auto --exclude=".zsh_history" "${DOTS}" "${ZSH}" "${HOME}/.zshenv"
